import Head from 'next/head'
import Image from 'next/image'
import { Roboto } from 'next/font/google'
import { Calendar } from '../components/Calendar'

const roboto = Roboto({ weight: "400", subsets: ['latin'] })

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={roboto.className}>
				<Calendar />
			</main>
		</>
	)
}
